### ISSUE TITLE
Allow the user to replace existing functions

### ISSUE THREAD

**Issue by fungiboletus** [dapaas/grafterizer#11]
`Couldn't add custom function. A function with the same name already exists.` is not userfriendly. We need to either automatically replace the existing function, or ask the user if she wants to replace it (showing the diff' between the old and the new function).

**Comment by nvnikolov** [comment]
This was caused by a bug that was fixed in commit f96ec7e (29 June). Current implementation automatically overwrites any existing function with the same name. Adding the diff prompt for the user will be implemented next.

**Comment by fungiboletus** [comment]
This should be fixed.

![2015-08-06 15_44_30-new transformation - grafterizer](https://cloud.githubusercontent.com/assets/45740/9112915/0ca62d78-3c52-11e5-8356-0a430d4f512a.png)
