### ISSUE TITLE
Special characters do not get parsed properly

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#132]
Special characters (e.g. 'ø', 'æ' 'å') do not get parsed properly and appear as question marks in the UI.

![image](https://cloud.githubusercontent.com/assets/8124245/11499601/6838860a-9827-11e5-8e43-a9c02e9001f1.png)

(this may be caused by the back-end services)

**Comment by dinans** [comment]
This issue was moved to datagraft/grafterizer#14
