### ISSUE TITLE
sort-dataset utility function throws strange exceptions

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#156]
Attempting to transform the following data:
![image](https://cloud.githubusercontent.com/assets/8124245/14077864/98c722ce-f4f0-11e5-89b2-0c61f5c03f30.png)

The result is an exception which makes no sense:
![image](https://cloud.githubusercontent.com/assets/8124245/14077869/b0a4673a-f4f0-11e5-8407-9a13f3457d94.png)

**Comment by dinans** [comment]
This issue was moved to datagraft/grafterizer#4
