### ISSUE TITLE
Cannot specify numeric column names for make-dataset with the "Specify column names" option

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#157]
The implementation should be changed to use the clojure "keyword" function instead of attempting to create keywords directly.
E.g., generate:
(keyword "234")
instead of:
:234

**Comment by nvnikolov** [comment]
May not be possible but still has to be investigated. 
See: https://github.com/Swirrl/grafter/issues/63

**Comment by dinans** [comment]
This issue was moved to datagraft/grafterizer#3
