### ISSUE TITLE
Error message: "Error -1 while contacting server"

### ISSUE THREAD

**Issue by bmzernichow** [dapaas/grafterizer#161]
"Error -1 while contacting server" appears when accessing datagraft.net/pages/transformations or trying to create a new transformation by either uploading a file or using an existing distribution (see print screen). No transformations available and not possible to edit existing transformations. Same error message when accessing/ viewing public transformations.

![dg error](https://cloud.githubusercontent.com/assets/11430375/16924681/d65b71d4-4d20-11e6-838a-3d409abfb87c.png)

**Comment by nvnikolov** [comment]
Error was due to an expired SSL certificate and has now been fixed
