### ISSUE TITLE
The tabular data is download as EDN and not CSV

### ISSUE THREAD

**Issue by fungiboletus** [dapaas/grafterizer#58]
When the transformation doesn't contain a RDF mapping, the processed data format is EDN (and not CSV).

Is this critical ?

@nvnikolov Should we convert the data to CSV before the next milestone?

**Comment by nvnikolov** [comment]
@yellowiscool no - we still support CSV download from the grid control

**Comment by nvnikolov** [comment]
This looks like it has been fixed now - @yellowiscool please confirm and close if so

**Comment by fungiboletus** [comment]
:ok:
