### ISSUE TITLE
"Add a new pipeline function" is empty sometimes

### ISSUE THREAD

**Issue by fungiboletus** [dapaas/grafterizer#67]
I have no explanation :/

![itmightbewrong](https://cloud.githubusercontent.com/assets/45740/9304820/89c4344c-44ec-11e5-8947-39eb718b0529.png)

**Comment by fungiboletus** [comment]
It might be a $mdDialog bug when using monkey testing. $mdDialog.hide and $mdDialog.cancel are broken sometimes.

**Comment by nvnikolov** [comment]
In fact, until you select a function type, you cannot select "Cancel":
![image](https://cloud.githubusercontent.com/assets/8124245/9306728/7527586c-44fa-11e5-8b8a-f089a9e55fca.png)

**Comment by fungiboletus** [comment]
This should be fixed :D
