### ISSUE TITLE
Test how many users can concurrently use Grafterizer

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#68]

**Comment by fungiboletus** [comment]
The monkeys don't simulate drag&drop of files and almost never manage to open an existing file.

Instead we can maybe use [SeleniumHQ](http://www.seleniumhq.org/) <sup>or similar</sup> and make a real test suite.

**Comment by fungiboletus** [comment]
If it's only for the backend, we can use JMeter <sup>or similar</sup>.

**Comment by nvnikolov** [comment]
I think should use SeleniumHQ as:
- in the UI we have throttling
- we should also test back-end services that are not associated with the transformations server

**Comment by fungiboletus** [comment]
- With 100 users, everything is alright.
- With 100 000 users, an API called by Grafterizer crashed.

100 users is good enough, we can conduct better tests using JMeter, Selenium or Gatling later.
