### ISSUE TITLE
Output RDF data gets downloaded twice

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#69]
When you click the button for download, the data gets downloaded twice

**Comment by fungiboletus** [comment]
Happens only with Chrome on Desktop. It works fine with Firefox or Chrome on mobile, or Chrome on desktop emulating mobile from the developer tools.

We can look into it later, but I don't have time for 2.0

**Comment by fungiboletus** [comment]
|(°͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌°͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌°͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌°͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌͌)_|
