### ISSUE TITLE
Refactor pipeline functions dialogs

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#80]
- Every dialog which implements more than one prototype of a function (e.g. make-dataset can be used with both move-first-row-to-header, or column name) should have the non-used option(s) for specification disabled in the UI
- Align the select controls with the labels for functions: add-column (custom expression), derive-column (function to derive with and its argument), map columns
- Filter-rows - align "Text to match" with "ignore case"
- Filter-rows - regular expression uses normal input control (use angular-material)
- Filter-rows - help for regular expressions uses too high font size
- Rename-columns dialog needs to be refactored - content becomes too large for the dialog when adding functions to transform with with long names
- Rename-columns - "Transform current column names" does not look well in the small space - refactor or rephrase it

**Comment by dinans** [comment]
This issue was moved to datagraft/grafterizer#21
