### ISSUE TITLE
Optimise previews in UI

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#87]
Minimise the communication with Graftwerk when previewing transformation through caching, implementing simple functions in the client side, etc.

**Comment by fungiboletus** [comment]
Can we say this is fixed?

**Comment by nvnikolov** [comment]
No - we need to design and implement caching on the client side first :rocket:

**Comment by nvnikolov** [comment]
This was fixed and is available with the latest version of the Grafterizer backend
