### ISSUE TITLE
Fix error reporting for RDF mapping errors

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/grafterizer#93]
Sometimes when the RDF mapping is incorrect there is no error displayed in the UI (or sent by the back-end for that matter). The result is simply an empty file with no information on what went wrong :crying_cat_face:

**Comment by fungiboletus** [comment]
When an error occurs, the backend directly connects the Graftwerk output to the response stream. It means Graftwerk returns nothing. We could check on the frontend if the result is empty and display an random error message if it's the case.

**Comment by dinans** [comment]
This issue was moved to datagraft/grafterizer#17
